---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: bank-run-
spec:
  pipelineRef:
    name: example-bank
  resources:
  - name: bank-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/MonicaGarridoCamacho/bankBackend.git
        - name: revision
          value: main
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  serviceAccountName: pipeline
