apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-bank
spec:
  resources:
    - name: bank-git
      type: git
  params:
    - default: bank-app-backend
      name: APP_NAME
      type: string
    - default: 'https://github.com/MonicaGarridoCamacho/bankBackend'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: -repo
          workspace: local-maven-repo
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.host.url=https://sonarqube-bank-infra.apps.cluster-d7qxw.d7qxw.sandbox2290.opentlc.com'
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipITs'
            - '-Darguments=-DskipITs'
      resources:
        inputs:
          - name: source
            resource: bank-git
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: build
      params:
        - name: GOALS
          value: ["package"]
      resources:
        inputs:
          - name: source
            resource: bank-git
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - code-analysis
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: local-maven-repo
