apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-bank
spec:
  resources:
    - name: bank-git
      type: git
  params:
    - default: bank-app-backend
      name: APP_NAME
      type: string
    - default: 'https://github.com/MonicaGarridoCamacho/bankBackend'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: -repo
          workspace: local-maven-repo
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.login=admin'
            - '-Dsonar.password=admin'
            - '-Dsonar.host.url=https://sonarqube-devops.apps.cluster-d7qxw.d7qxw.sandbox2290.opentlc.com'
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipITs'
            - '-Darguments=-DskipITs'
      resources:
        inputs:
          - name: source
            resource: bank-git
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: build
      params:
        - name: GOALS
          value: ["package"]
      resources:
        inputs:
          - name: source
            resource: bank-git
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - code-analysis
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: deploys
      params:
        - name: VERSION
          value: latest
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: quay.io/monica_garrido/bank-backend
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value: []
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: local-maven-repo
  workspaces:
    - name: local-maven-repo
  
