apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-bank
spec:
  resources:
    - name: bank-git
      type: git
    - name: transaction-image
      type: image
    - name: user-image
      type: image
    - name: ui-image
      type: image
  tasks:
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.host.url=https://sonarqube-bank-infra.apps.cluster-brsdz.brsdz.sandbox1933.opentlc.com'
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipITs'
            - '-Darguments=-DskipITs'
      resources:
        inputs:
          - name: source
            resource: bank-git
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: deploy-transaction
      params:
        - name: COMMANDS
          value: >
            oc apply -f
            https://github.com/MonicaGarridoCamacho/bankBackend/blob/main/deployment.yaml
            -n example-bank
      runAfter:
        - code-analysis
      taskRef:
        kind: Task
        name: openshift-client
  workspaces:
    - name: local-maven-repo
